-- ============================================================
-- LAB DATABASE
-- Migration: V1
-- Description: Initial schema
-- Database: Oracle
-- ============================================================

-- ============================================================
-- 0. DROP EXISTING TABLES
-- ============================================================

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE LAB_CRAWLED_RECORD CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE LAB_CHANNEL CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE LAB_USER_DOMAIN CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE LAB_USER_INFO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE LAB_AUTH_USER CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE LAB_DOMAIN CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
END IF;
END;
/


-- ============================================================
-- 1. LAB_AUTH_USER
-- ============================================================
-- Authentication / authorization information
-- ============================================================

CREATE TABLE LAB_AUTH_USER (
                               ID VARCHAR2(25)
                                   CONSTRAINT PK_LAB_AUTH_USER
                                       PRIMARY KEY,

                               USERNAME VARCHAR2(100)
                                   CONSTRAINT UK_LAB_AUTH_USER_USERNAME
                                       UNIQUE
                                   NOT NULL,

                               PASSWORD_HASH VARCHAR2(255)
                                   NOT NULL,

                               ROLE VARCHAR2(20)
                                   NOT NULL,

                               STATUS VARCHAR2(20)
                                   NOT NULL,

                               CREATED_AT TIMESTAMP
                                   DEFAULT SYSTIMESTAMP
                                   NOT NULL,

                               UPDATED_AT TIMESTAMP
                                   DEFAULT SYSTIMESTAMP
                                   NOT NULL
);


-- ============================================================
-- 2. LAB_USER_INFO
-- ============================================================
-- User profile / personal information
-- ============================================================

CREATE TABLE LAB_USER_INFO (
                               USER_ID VARCHAR2(25)
                                   CONSTRAINT PK_LAB_USER_INFO
                                       PRIMARY KEY,

                               FULL_NAME VARCHAR2(255),

                               EMAIL VARCHAR2(255)
                                   CONSTRAINT UK_LAB_USER_INFO_EMAIL
                                       UNIQUE,

                               PHONE_NUMBER VARCHAR2(30),

                               AVATAR_URL VARCHAR2(1000),

                               DATE_OF_BIRTH DATE,

                               CREATED_AT TIMESTAMP
                                   DEFAULT SYSTIMESTAMP
                                   NOT NULL,

                               UPDATED_AT TIMESTAMP
                                   DEFAULT SYSTIMESTAMP
                                   NOT NULL,

                               CONSTRAINT FK_LAB_USER_INFO_AUTH_USER
                                   FOREIGN KEY (USER_ID)
                                       REFERENCES LAB_AUTH_USER (ID)
);


-- ============================================================
-- 3. LAB_DOMAIN
-- ============================================================

CREATE TABLE LAB_DOMAIN (
                            ID NUMBER(19)
                                GENERATED BY DEFAULT AS IDENTITY
                                CONSTRAINT PK_LAB_DOMAIN
                                    PRIMARY KEY,

                            CODE VARCHAR2(50)
                                CONSTRAINT UK_LAB_DOMAIN_CODE
                                    UNIQUE
                                NOT NULL,

                            NAME VARCHAR2(255)
                                NOT NULL,

                            STATUS VARCHAR2(20)
                                NOT NULL,

                            CREATED_AT TIMESTAMP
                                DEFAULT SYSTIMESTAMP
                                NOT NULL,

                            CREATED_BY VARCHAR2(25)
                                NOT NULL,

                            UPDATED_AT TIMESTAMP,

                            UPDATED_BY VARCHAR2(25)
);


-- ============================================================
-- 4. LAB_USER_DOMAIN
-- ============================================================

CREATE TABLE LAB_USER_DOMAIN (
                                 ID NUMBER(19)
                                     GENERATED BY DEFAULT AS IDENTITY
                                     CONSTRAINT PK_LAB_USER_DOMAIN
                                         PRIMARY KEY,

                                 USER_ID VARCHAR2(25)
                                     NOT NULL,

                                 DOMAIN_ID NUMBER(19)
                                     NOT NULL,

                                 ASSIGNED_AT TIMESTAMP
                                     DEFAULT SYSTIMESTAMP
                                     NOT NULL,

                                 ASSIGNED_BY VARCHAR2(25)
                                     NOT NULL,

                                 REVOKED_AT TIMESTAMP,

                                 REVOKED_BY VARCHAR2(25),

                                 CONSTRAINT FK_LAB_USER_DOMAIN_USER
                                     FOREIGN KEY (USER_ID)
                                         REFERENCES LAB_AUTH_USER (ID),

                                 CONSTRAINT FK_LAB_USER_DOMAIN_DOMAIN
                                     FOREIGN KEY (DOMAIN_ID)
                                         REFERENCES LAB_DOMAIN (ID)
);


-- ============================================================
-- 5. LAB_CHANNEL
-- ============================================================

CREATE TABLE LAB_CHANNEL (
                             ID NUMBER(19)
                                 GENERATED BY DEFAULT AS IDENTITY
                                 CONSTRAINT PK_LAB_CHANNEL
                                     PRIMARY KEY,

                             DOMAIN_ID NUMBER(19)
                                 NOT NULL,

                             NAME VARCHAR2(255)
                                 NOT NULL,

                             PLATFORM_TYPE VARCHAR2(50)
                                 NOT NULL,

                             STATUS VARCHAR2(20)
                                 NOT NULL,

                             SOURCE_URL VARCHAR2(1000),

                             CONFIG CLOB,

                             CREATED_AT TIMESTAMP
                                 DEFAULT SYSTIMESTAMP
                                 NOT NULL,

                             CREATED_BY VARCHAR2(25)
                                 NOT NULL,

                             UPDATED_AT TIMESTAMP,

                             UPDATED_BY VARCHAR2(25),

                             CONSTRAINT FK_LAB_CHANNEL_DOMAIN
                                 FOREIGN KEY (DOMAIN_ID)
                                     REFERENCES LAB_DOMAIN (ID)
);


-- ============================================================
-- 6. LAB_CRAWLED_RECORD
-- ============================================================

CREATE TABLE LAB_CRAWLED_RECORD (
                                    ID NUMBER(19)
                                        GENERATED BY DEFAULT AS IDENTITY
                                        CONSTRAINT PK_LAB_CRAWLED_RECORD
                                            PRIMARY KEY,

                                    CHANNEL_ID NUMBER(19)
                                        NOT NULL,

                                    TITLE VARCHAR2(500),

                                    CONTENT CLOB,

                                    PUBLISHED_AT TIMESTAMP,

                                    CRAWLED_AT TIMESTAMP
                                        DEFAULT SYSTIMESTAMP
                                        NOT NULL,

                                    PROCESSING_STATUS VARCHAR2(20)
                                        NOT NULL,

                                    ERROR_MESSAGE VARCHAR2(1000),

                                    CREATED_AT TIMESTAMP
                                        DEFAULT SYSTIMESTAMP
                                        NOT NULL,

                                    CONSTRAINT FK_LAB_CRAWLED_RECORD_CHANNEL
                                        FOREIGN KEY (CHANNEL_ID)
                                            REFERENCES LAB_CHANNEL (ID)
);


-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX IDX_LAB_USER_DOMAIN_USER
    ON LAB_USER_DOMAIN (USER_ID);

CREATE INDEX IDX_LAB_USER_DOMAIN_DOMAIN
    ON LAB_USER_DOMAIN (DOMAIN_ID);

CREATE INDEX IDX_LAB_CHANNEL_DOMAIN
    ON LAB_CHANNEL (DOMAIN_ID);

CREATE INDEX IDX_LAB_CRAWLED_RECORD_CHANNEL
    ON LAB_CRAWLED_RECORD (CHANNEL_ID);

CREATE INDEX IDX_LAB_CRAWLED_RECORD_STATUS
    ON LAB_CRAWLED_RECORD (PROCESSING_STATUS);